version: "3.5"

volumes:
  grafana_data:
  private_grafana_data:
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./go-carbon-storage/whisper:/go-carbon-storage
      - ./logs/api:/app/logs
    environment:
     - GRAFANA_URL=http://grafana:3000
     - GRAFANA_USER=admin
     - GRAFANA_PASSWORD=password
    networks:
      - frontend
      - backend
  carbon-relay-ng:
    image: grafana/carbon-relay-ng
    depends_on:
      - go-carbon
    volumes:
      - ./config/carbon-relay-ng:/conf
    ports:
      - "2003:2003"
    healthcheck:
      test: nc -zv localhost 2003
      interval: 10s
      timeout: 1s
      retries: 3
    networks:
      - frontend
      - backend
  go-carbon:
    image: ghcr.io/go-graphite/go-carbon:latest
    volumes:
      - ./config/go-carbon/go-carbon.conf:/etc/go-carbon/go-carbon.conf
      - ./config/go-carbon:/conf
      - ./go-carbon-storage:/go-carbon-storage
      - ./logs/gocarbon:/log
    healthcheck:
      test: "curl -fsSL -o /dev/null 'http://localhost:8080/metrics/find/?query=*&format=json'"
      interval: 10s
      timeout: 1s
      retries: 3
    networks:
      - backend
  carbonapi:
    image: carbonapi
    volumes:
      - ./config/carbonapi/carbonapi.yml:/etc/carbonapi.yml
      # - ./config/carbonapi/timeShift.yaml:/conf/timeShift.yaml:ro
      # - ./config/carbonapi/graphTemplates.yaml:/conf/graphTemplates.yaml:ro
      # - ./config/carbonapi/graphiteWeb.yaml:/conf/graphiteWeb.yaml:ro
      # - ./config/carbonapi/aliasByRedis.yaml:/conf/aliasByRedis.yaml:ro
      # - ./config/carbonapi/moving.yaml:/conf/moving.yaml:ro
      - ./config/carbonapi:/conf:ro
      - ./logs/carbonapi:/log
    depends_on:
      - carbon-relay-ng
    healthcheck:
      test: "curl -fsSL -o /dev/null http://localhost:8080/lb_check"
      interval: 10s
      timeout: 1s
      retries: 3
    networks:
      - backend
  stats-gateway:
    image: stats-gateway
    depends_on:
      - carbonapi
      - grafana
    environment:
     - BACKEND_URL=http://carbonapi:8081
     - GRAFANA_URL=http://grafana:3000
    networks:
      - backend
      - frontend
  grafana:
    image: grafana/grafana-oss:9.0.4-ubuntu
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana:/etc/grafana
      - ./logs/grafana:/var/log/grafana
    ports:
      - 3000:3000
    depends_on:
      - carbon-relay-ng
    healthcheck:
      test: "curl -fsSL -o /dev/null http://localhost:3000/login"
      interval: 10s
      timeout: 1s
      retries: 3
    networks:
      - frontend
  private_grafana:
    image: grafana/grafana-oss:9.0.4-ubuntu
    volumes:
      - private_grafana_data:/var/lib/grafana
      - ./config/grafana:/etc/grafana
      - ./logs/privategrafana:/var/log/grafana
    ports:
      - 3001:3000
    depends_on:
      - carbon-relay-ng
    healthcheck:
      test: "curl -fsSL -o /dev/null http://localhost:3000/login"
      interval: 10s
      timeout: 1s
      retries: 3
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend: