{
 "title": "Stats",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GCL Level",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "screeps.stats.*.gcl.level" }
   ]
  },
  {
   "title": "Cpu Bucket",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 6, "y": 1 },
   "targets": [
    {
     "target": "aliasByNode(screeps.stats.*.cpu.bucket, 2, 4)"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 1 },
   "targets": [
    {
     "target": "aliasByNode(screeps.stats.*.cpu.usage, 2, 4)"
    },
    {
     "target": "aliasByNode(screeps.stats.*.cpu.limit, 2, 4)"
    }
   ]
  },
  {
   "title": "Leaderboard",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "screeps.stats.*.leaderboard.rank"
    }
   ]
  },
  {
   "title": "GPL Level",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "screeps.stats.*.gpl.level" }
   ]
  },
  {
   "title": "Room count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "screeps.stats.*.roomCount" }
   ]
  },
  {
   "title": "Creep count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "screeps.stats.*.creepCount" }
   ]
  },
  {
   "title": "Spawn count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "screeps.stats.*.spawnCount" }
   ]
  },
  {
   "title": "Construction count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "screeps.stats.*.constructionSiteCount"
    }
   ]
  },
  {
   "title": "Flag count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "screeps.stats.*.flagCount" }
   ]
  },
  { "title": "Rooms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "RCL level",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "screeps.stats.*.rooms.*.controller.level"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "target": "aliasByNode(screeps.stats.*.rooms.*.energyInStorage, 2, 4)"
    }
   ]
  },
  {
   "title": "Terminal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "target": "aliasByNode(screeps.stats.*.rooms.*.energyInTerminal, 2, 4)"
    }
   ]
  },
  {
   "title": "Energy available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "target": "aliasByNode(screeps.stats.*.rooms.*.energyAvailable, 2, 4)"
    }
   ]
  },
  {
   "title": "Energy capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "target": "aliasByNode(screeps.stats.*.rooms.*.energyCapacityAvailable, 2, 4)"
    }
   ]
  }
 ]
}