{
 "title": "ServerStats",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Hosts", "query": "screeps.serverStats.*" },
   { "name": "Users", "query": "screeps.serverStats.$Hosts.*" },
   {
    "name": "Rooms",
    "query": "screeps.serverStats.$Hosts.$Users.$RoomType.*"
   },
   { "name": "RoomType", "query": "owned,reserved" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Controller level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.controller.level), 4, 6)"
    }
   ]
  },
  {
   "title": "Controller percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(divideSeriesLists(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.controller.progress, #B)), 4, 6)",
     "targetFull": "aliasByNode(removeZeroSeries(divideSeriesLists(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.controller.progress, screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.controller.progressTotal)), 4, 6)"
    }
   ]
  },
  {
   "title": "Total creeps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "groupByNodes(removeZeroSeries(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.creepCounts), 'sum', 4)"
    }
   ]
  },
  {
   "title": "Total structures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "target": "groupByNodes(removeZeroSeries(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.structureCounts.*), 'sum', 4, 7)"
    }
   ]
  },
  {
   "title": "CS Total progress %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(divideSeriesLists(groupByNodes(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.constructionSites.progress, 'sum', 4, 6), #B)), 0, 1)",
     "targetFull": "aliasByNode(removeZeroSeries(divideSeriesLists(groupByNodes(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.constructionSites.progress, 'sum', 4, 6), groupByNodes(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.constructionSites.total, 'sum', 4, 6))), 0, 1)"
    }
   ]
  },
  {
   "title": "Energy in Spawn & Extensions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "target": "groupByNodes(removeZeroSeries(movingAverage(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.structureStore.{extension,spawn}.energy, 10)), 'sum', 4, 6)"
    }
   ]
  },
  {
   "title": "User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(screeps.serverStats.$Hosts.$Users.user.lastUsedCpu), 4)"
      }
     ]
    },
    {
     "title": "GCL",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(screeps.serverStats.$Hosts.$Users.user.gcl), 4)"
      }
     ]
    },
    {
     "title": "CPU bucket",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(screeps.serverStats.$Hosts.$Users.user.cpuAvailable), 4)"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Controller level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.controller.level), 4, 6)"
      }
     ]
    },
    {
     "title": "Controller percentage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(divideSeriesLists(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.controller.progress, #B)), 4, 6)",
       "targetFull": "aliasByNode(removeZeroSeries(divideSeriesLists(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.controller.progress, screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.controller.progressTotal)), 4, 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "Creeps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Energy in creeps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(movingAverage(groupByNodes(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.creepStore.energy, 'sum', 4, 6), 5)), 0, 1)"
      }
     ]
    },
    {
     "title": "Total creeps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "target": "groupByNodes(removeZeroSeries(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.creepCounts), 'sum', 4, 7)"
      }
     ]
    },
    {
     "title": "Total parts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(movingAverage(groupByNodes(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.creepBodies.*, 'sum', 4, 6), 5)), 0, 1)"
      }
     ]
    },
    {
     "title": "Total parts per type",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasByNode(groupByNodes(removeZeroSeries(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.creepBodies.*), 'sum', 8), 0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Structures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Energy in Spawn & Extensions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "target": "groupByNodes(removeZeroSeries(movingAverage(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.structureStore.{extension,spawn}.energy, 5)), 'sum', 4, 6)"
      }
     ]
    },
    {
     "title": "Total structures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "target": "groupByNodes(removeZeroSeries(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.structureCounts.*), 'sum', 4, 6)"
      }
     ]
    },
    {
     "title": "Energy in container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "target": "groupByNodes(removeZeroSeries(movingAverage(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.structureStore.container.energy, 5)), 'sum', 4)"
      }
     ]
    },
    {
     "title": "Total structures per type",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "groupByNodes(removeZeroSeries(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.structureCounts.*), 'sum', 8)"
      }
     ]
    }
   ]
  },
  {
   "title": "Construction sites",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total progress %",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(divideSeriesLists(groupByNodes(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.constructionSites.progress, 'sum', 4, 6), #B)), 0, 1)",
       "targetFull": "aliasByNode(removeZeroSeries(divideSeriesLists(groupByNodes(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.constructionSites.progress, 'sum', 4, 6), groupByNodes(screeps.serverStats.$Hosts.$Users.$RoomType.$Rooms.constructionSites.total, 'sum', 4, 6))), 0, 1)"
      }
     ]
    }
   ]
  },
  {
   "title": "Dropped energy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Energy on ground",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "target": "groupByNodes(removeZeroSeries(screeps.serverStats.$Hosts.$Rooms.$RoomType.$Rooms.droppedEnergy), 'sum', 4, 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "Mineral",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mineral amount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "target": "groupByNodes(removeZeroSeries(screeps.serverStats.$Hosts.$Rooms.$RoomType.$Rooms.mineralAmount), 'sum', 4, 6)"
      }
     ]
    }
   ]
  }
 ]
}